THREE.OrbitControls=function(C,w,x){function y(b){if(!1!==a.enabled){b.preventDefault();var c=a.domElement===document?a.domElement.body:a.domElement;if(e===d.ROTATE){if(!0===a.noRotate)return;f.set(b.clientX,b.clientY);g.subVectors(f,h);a.rotateLeft(2*Math.PI*g.x/c.clientWidth*a.rotateSpeed);a.rotateUp(2*Math.PI*g.y/c.clientHeight*a.rotateSpeed);h.copy(f)}else if(e===d.DOLLY){if(!0===a.noZoom)return;k.set(b.clientX,b.clientY);p.subVectors(k,l);0<p.y?a.dollyIn():a.dollyOut();l.copy(k)}else if(e===
d.PAN){if(!0===a.noPan)return;m.set(b.clientX,b.clientY);q.subVectors(m,n);a.pan(q);n.copy(m)}a.update()}}function z(){!1!==a.enabled&&(a.domElement.removeEventListener("mousemove",y,!1),a.domElement.removeEventListener("mouseup",z,!1),e=d.NONE)}function A(b){if(!1!==a.enabled&&!0!==a.noZoom){var c=0;b.wheelDelta?c=b.wheelDelta:b.detail&&(c=-b.detail);0<c?a.dollyOut():a.dollyIn()}}this.object=C;this.domElement=void 0!==w?w:document;this.localElement=void 0!==x?x:document;this.enabled=!0;this.center=
this.target=new THREE.Vector3;this.noZoom=!1;this.zoomSpeed=1;this.minDistance=0;this.maxDistance=Infinity;this.noRotate=!1;this.rotateSpeed=1;this.noPan=!1;this.keyPanSpeed=7;this.autoRotate=!1;this.autoRotateSpeed=2;this.minPolarAngle=0;this.maxPolarAngle=Math.PI;this.noKeys=!1;this.keys={LEFT:37,UP:38,RIGHT:39,BOTTOM:40};var a=this,h=new THREE.Vector2,f=new THREE.Vector2,g=new THREE.Vector2,n=new THREE.Vector2,m=new THREE.Vector2,q=new THREE.Vector2,l=new THREE.Vector2,k=new THREE.Vector2,p=new THREE.Vector2,
u=0,v=0,r=1,t=new THREE.Vector3,B=new THREE.Vector3,d={NONE:-1,ROTATE:0,DOLLY:1,PAN:2,TOUCH_ROTATE:3,TOUCH_DOLLY:4,TOUCH_PAN:5},e=d.NONE,D={type:"change"};this.rotateLeft=function(b){void 0===b&&(b=2*Math.PI/60/60*a.autoRotateSpeed);v-=b};this.rotateUp=function(b){void 0===b&&(b=2*Math.PI/60/60*a.autoRotateSpeed);u-=b};this.panLeft=function(a){var b=new THREE.Vector3,d=this.object.matrix.elements;b.set(d[0],d[1],d[2]);b.multiplyScalar(-a);t.add(b)};this.panUp=function(a){var b=new THREE.Vector3,d=
this.object.matrix.elements;b.set(d[4],d[5],d[6]);b.multiplyScalar(a);t.add(b)};this.pan=function(b){var c=a.domElement===document?a.domElement.body:a.domElement;if(void 0!==a.object.fov){var d=a.object.position.clone().sub(a.target).length();d*=Math.tan(a.object.fov/2*Math.PI/180);a.panLeft(2*b.x*d/c.clientHeight);a.panUp(2*b.y*d/c.clientHeight)}else void 0!==a.object.top?(a.panLeft(b.x*(a.object.right-a.object.left)/c.clientWidth),a.panUp(b.y*(a.object.top-a.object.bottom)/c.clientHeight)):console.warn("WARNING: OrbitControls.js encountered an unknown camera type - pan disabled.")};
this.dollyIn=function(b){void 0===b&&(b=Math.pow(.95,a.zoomSpeed));r/=b};this.dollyOut=function(b){void 0===b&&(b=Math.pow(.95,a.zoomSpeed));r*=b};this.update=function(){var b=this.object.position,c=b.clone().sub(this.target),d=Math.atan2(c.x,c.z),e=Math.atan2(Math.sqrt(c.x*c.x+c.z*c.z),c.y);this.autoRotate&&this.rotateLeft(2*Math.PI/60/60*a.autoRotateSpeed);d+=v;e+=u;e=Math.max(this.minPolarAngle,Math.min(this.maxPolarAngle,e));e=Math.max(1E-6,Math.min(Math.PI-1E-6,e));var f=c.length()*r;f=Math.max(this.minDistance,
Math.min(this.maxDistance,f));this.target.add(t);c.x=f*Math.sin(e)*Math.sin(d);c.y=f*Math.cos(e);c.z=f*Math.sin(e)*Math.cos(d);b.copy(this.target).add(c);this.object.lookAt(this.target);u=v=0;r=1;t.set(0,0,0);0<B.distanceTo(this.object.position)&&(this.dispatchEvent(D),B.copy(this.object.position))};this.domElement.addEventListener("contextmenu",function(a){a.preventDefault()},!1);this.localElement.addEventListener("mousedown",function(b){if(!1!==a.enabled){b.preventDefault();if(0===b.button){if(!0===
a.noRotate)return;e=d.ROTATE;h.set(b.clientX,b.clientY)}else if(1===b.button){if(!0===a.noZoom)return;e=d.DOLLY;l.set(b.clientX,b.clientY)}else if(2===b.button){if(!0===a.noPan)return;e=d.PAN;n.set(b.clientX,b.clientY)}a.domElement.addEventListener("mousemove",y,!1);a.domElement.addEventListener("mouseup",z,!1)}},!1);this.domElement.addEventListener("mousewheel",A,!1);this.domElement.addEventListener("DOMMouseScroll",A,!1);this.domElement.addEventListener("keydown",function(b){if(!1!==a.enabled&&
!0!==a.noKeys&&!0!==a.noPan){var c=!1;switch(b.keyCode){case a.keys.UP:a.pan(new THREE.Vector2(0,a.keyPanSpeed));c=!0;break;case a.keys.BOTTOM:a.pan(new THREE.Vector2(0,-a.keyPanSpeed));c=!0;break;case a.keys.LEFT:a.pan(new THREE.Vector2(a.keyPanSpeed,0));c=!0;break;case a.keys.RIGHT:a.pan(new THREE.Vector2(-a.keyPanSpeed,0)),c=!0}c&&a.update()}},!1);this.localElement.addEventListener("touchstart",function(b){if(!1!==a.enabled)switch(b.touches.length){case 1:if(!0===a.noRotate)break;e=d.TOUCH_ROTATE;
h.set(b.touches[0].pageX,b.touches[0].pageY);break;case 2:if(!0===a.noZoom)break;e=d.TOUCH_DOLLY;var c=b.touches[0].pageX-b.touches[1].pageX;b=b.touches[0].pageY-b.touches[1].pageY;l.set(0,Math.sqrt(c*c+b*b));break;case 3:if(!0===a.noPan)break;e=d.TOUCH_PAN;n.set(b.touches[0].pageX,b.touches[0].pageY);break;default:e=d.NONE}},!1);this.domElement.addEventListener("touchend",function(){!1!==a.enabled&&(e=d.NONE)},!1);this.domElement.addEventListener("touchmove",function(b){if(!1!==a.enabled){b.preventDefault();
b.stopPropagation();var c=a.domElement===document?a.domElement.body:a.domElement;switch(b.touches.length){case 1:if(!0===a.noRotate)break;if(e!==d.TOUCH_ROTATE)break;f.set(b.touches[0].pageX,b.touches[0].pageY);g.subVectors(f,h);a.rotateLeft(2*Math.PI*g.x/c.clientWidth*a.rotateSpeed);a.rotateUp(2*Math.PI*g.y/c.clientHeight*a.rotateSpeed);h.copy(f);break;case 2:if(!0===a.noZoom)break;if(e!==d.TOUCH_DOLLY)break;c=b.touches[0].pageX-b.touches[1].pageX;b=b.touches[0].pageY-b.touches[1].pageY;k.set(0,
Math.sqrt(c*c+b*b));p.subVectors(k,l);0<p.y?a.dollyOut():a.dollyIn();l.copy(k);break;case 3:if(!0===a.noPan)break;if(e!==d.TOUCH_PAN)break;m.set(b.touches[0].pageX,b.touches[0].pageY);q.subVectors(m,n);a.pan(q);n.copy(m);break;default:e=d.NONE}}},!1)};THREE.OrbitControls.prototype=Object.create(THREE.EventDispatcher.prototype);
