(function(){function V(a){var c=new Map;"Connections"in a&&a.Connections.connections.forEach(function(a){var b=a[0],e=a[1];a=a[2];c.has(b)||c.set(b,{parents:[],children:[]});var f={ID:e,relationship:a};c.get(b).parents.push(f);c.has(e)||c.set(e,{parents:[],children:[]});b={ID:b,relationship:a};c.get(e).children.push(b)});return c}function W(a,c,b,d,e){var f={};c.BumpFactor&&(f.bumpScale=c.BumpFactor.value);c.Diffuse&&(f.color=(new THREE.Color).fromArray(c.Diffuse.value));c.DisplacementFactor&&(f.displacementScale=
c.DisplacementFactor.value);c.ReflectionFactor&&(f.reflectivity=c.ReflectionFactor.value);c.Specular&&(f.specular=(new THREE.Color).fromArray(c.Specular.value));c.Shininess&&(f.shininess=c.Shininess.value);c.Emissive&&(f.emissive=(new THREE.Color).fromArray(c.Emissive.value));c.EmissiveFactor&&(f.emissiveIntensity=parseFloat(c.EmissiveFactor.value));c.Opacity&&(f.opacity=parseFloat(c.Opacity.value));1>f.opacity&&(f.transparent=!0);e.get(d).children.forEach(function(c){var d=c.relationship;switch(d){case "Bump":f.bumpMap=
b.get(c.ID);break;case "DiffuseColor":f.map=v(a,b,c.ID,e);break;case "DisplacementColor":f.displacementMap=v(a,b,c.ID,e);break;case "EmissiveColor":f.emissiveMap=v(a,b,c.ID,e);break;case "NormalMap":f.normalMap=v(a,b,c.ID,e);break;case "ReflectionColor":f.envMap=v(a,b,c.ID,e);f.envMap.mapping=THREE.EquirectangularReflectionMapping;break;case "SpecularColor":f.specularMap=v(a,b,c.ID,e);break;case "TransparentColor":f.alphaMap=v(a,b,c.ID,e);f.transparent=!0;break;default:console.warn("THREE.FBXLoader: %s map is not supported in three.js, skipping texture.",
d)}});return f}function v(a,c,b,d){"LayeredTexture"in a.Objects&&b in a.Objects.LayeredTexture&&(console.warn("THREE.FBXLoader: layered textures are not supported in three.js. Discarding all but first layer."),b=d.get(b).children[0].ID);return c.get(b)}function X(a,c){var b=[];a.children.forEach(function(a){var d=c[a.ID];"Cluster"===d.attrType&&(a={ID:a.ID,indices:[],weights:[],transform:(new THREE.Matrix4).fromArray(d.Transform.a),transformLink:(new THREE.Matrix4).fromArray(d.TransformLink.a),linkMode:d.Mode},
"Indexes"in d&&(a.indices=d.Indexes.a,a.weights=d.Weights.a),b.push(a))});return{rawBones:b,bones:[]}}function Y(a,c,b,d){var e=c.parents.map(function(b){return a.Objects.Model[b.ID]});if(0!==e.length){var f=c.children.reduce(function(a,b){void 0!==d[b.ID]&&(a=d[b.ID]);return a},null),g=new THREE.Matrix4;e=e[0];if("GeometricRotation"in e){var h=e.GeometricRotation.value.map(THREE.Math.degToRad);h[3]="ZYX";g.makeRotationFromEuler((new THREE.Euler).fromArray(h))}"GeometricTranslation"in e&&g.setPosition((new THREE.Vector3).fromArray(e.GeometricTranslation.value));
return Z(a,c,b,f,g)}}function Z(a,c,b,d,e){var f=b.Vertices.a,g=b.PolygonVertexIndex.a,h=[],l=[],k=[],m=[],n=[],q=[],r=[];if(b.LayerElementColor)var I=aa(b.LayerElementColor[0]);if(b.LayerElementMaterial)var w=ba(b.LayerElementMaterial[0]);if(b.LayerElementNormal)var x=ca(b.LayerElementNormal[0]);if(b.LayerElementUV){var J=[];for(a=0;b.LayerElementUV[a];)J.push(da(b.LayerElementUV[a])),a++}var v={};null!==d&&d.rawBones.forEach(function(a,b){a.indices.forEach(function(c,d){void 0===v[c]&&(v[c]=[]);
v[c].push({id:b,weight:a.weights[d]})})});var A=0,F=0,H=!1,B=[],C=[],D=[],E=[],y=[],z=[];g.forEach(function(a,b){var c=!1;0>a&&(a^=-1,g[b]=a,c=!0);var e=[],t=[];B.push(3*a,3*a+1,3*a+2);if(I){var u=K[I.mappingType][I.referenceType](b,A,a,I);D.push(u[0],u[1],u[2])}if(d){void 0!==v[a]&&v[a].forEach(function(a){t.push(a.weight);e.push(a.id)});if(4<t.length){H||(console.warn("THREE.FBXLoader: Vertex has more than 4 skinning weights assigned to vertex. Deleting additional weights."),H=!0);var M=[0,0,0,
0],G=[0,0,0,0];t.forEach(function(a,b){var c=a,d=e[b];G.forEach(function(a,b,e){c>a&&(e[b]=c,c=a,a=M[b],M[b]=d,d=a)})});e=M;t=G}for(;4>t.length;)t.push(0),e.push(0);for(var p=0;4>p;++p)y.push(t[p]),z.push(e[p])}x&&(u=K[x.mappingType][x.referenceType](b,A,a,x),C.push(u[0],u[1],u[2]));if(w&&"AllSame"!==w.mappingType)var L=K[w.mappingType][w.referenceType](b,A,a,w)[0];J&&J.forEach(function(c,d){var e=K[c.mappingType][c.referenceType](b,A,a,c);void 0===E[d]&&(E[d]=[]);E[d].push(e[0]);E[d].push(e[1])});
F++;if(c){for(p=2;p<F;p++)h.push(f[B[0]]),h.push(f[B[1]]),h.push(f[B[2]]),h.push(f[B[3*(p-1)]]),h.push(f[B[3*(p-1)+1]]),h.push(f[B[3*(p-1)+2]]),h.push(f[B[3*p]]),h.push(f[B[3*p+1]]),h.push(f[B[3*p+2]]),d&&(q.push(y[0]),q.push(y[1]),q.push(y[2]),q.push(y[3]),q.push(y[4*(p-1)]),q.push(y[4*(p-1)+1]),q.push(y[4*(p-1)+2]),q.push(y[4*(p-1)+3]),q.push(y[4*p]),q.push(y[4*p+1]),q.push(y[4*p+2]),q.push(y[4*p+3]),r.push(z[0]),r.push(z[1]),r.push(z[2]),r.push(z[3]),r.push(z[4*(p-1)]),r.push(z[4*(p-1)+1]),r.push(z[4*
(p-1)+2]),r.push(z[4*(p-1)+3]),r.push(z[4*p]),r.push(z[4*p+1]),r.push(z[4*p+2]),r.push(z[4*p+3])),I&&(k.push(D[0]),k.push(D[1]),k.push(D[2]),k.push(D[3*(p-1)]),k.push(D[3*(p-1)+1]),k.push(D[3*(p-1)+2]),k.push(D[3*p]),k.push(D[3*p+1]),k.push(D[3*p+2])),w&&"AllSame"!==w.mappingType&&(n.push(L),n.push(L),n.push(L)),x&&(l.push(C[0]),l.push(C[1]),l.push(C[2]),l.push(C[3*(p-1)]),l.push(C[3*(p-1)+1]),l.push(C[3*(p-1)+2]),l.push(C[3*p]),l.push(C[3*p+1]),l.push(C[3*p+2])),J&&J.forEach(function(a,b){void 0===
m[b]&&(m[b]=[]);m[b].push(E[b][0]);m[b].push(E[b][1]);m[b].push(E[b][2*(p-1)]);m[b].push(E[b][2*(p-1)+1]);m[b].push(E[b][2*p]);m[b].push(E[b][2*p+1])});A++;F=0;B=[];C=[];D=[];E=[];y=[];z=[]}});var t=new THREE.BufferGeometry;t.name=b.name;b=new THREE.Float32BufferAttribute(h,3);e.applyToBufferAttribute(b);t.addAttribute("position",b);0<k.length&&t.addAttribute("color",new THREE.Float32BufferAttribute(k,3));d&&(t.addAttribute("skinIndex",new THREE.Float32BufferAttribute(r,4)),t.addAttribute("skinWeight",
new THREE.Float32BufferAttribute(q,4)),t.FBX_Deformer=d);0<l.length&&(b=new THREE.Float32BufferAttribute(l,3),(new THREE.Matrix3).getNormalMatrix(e).applyToBufferAttribute(b),t.addAttribute("normal",b));m.forEach(function(a,b){var c="uv"+(b+1).toString();0===b&&(c="uv");t.addAttribute(c,new THREE.Float32BufferAttribute(m[b],2))});if(w&&"AllSame"!==w.mappingType){var G=n[0],u=0;n.forEach(function(a,b){a!==G&&(t.addGroup(u,b-u,G),G=a,u=b)});0<t.groups.length&&(e=t.groups[t.groups.length-1],e=e.start+
e.count,e!==n.length&&t.addGroup(e,n.length-e,G));0===t.groups.length&&t.addGroup(0,n.length,n[0])}return t}function ca(a){var c=a.MappingInformationType,b=a.ReferenceInformationType,d=a.Normals.a,e=[];"IndexToDirect"===b&&("NormalIndex"in a?e=a.NormalIndex.a:"NormalsIndex"in a&&(e=a.NormalsIndex.a));return{dataSize:3,buffer:d,indices:e,mappingType:c,referenceType:b}}function da(a){var c=a.MappingInformationType,b=a.ReferenceInformationType,d=a.UV.a,e=[];"IndexToDirect"===b&&(e=a.UVIndex.a);return{dataSize:2,
buffer:d,indices:e,mappingType:c,referenceType:b}}function aa(a){var c=a.MappingInformationType,b=a.ReferenceInformationType,d=a.Colors.a,e=[];"IndexToDirect"===b&&(e=a.ColorIndex.a);return{dataSize:4,buffer:d,indices:e,mappingType:c,referenceType:b}}function ba(a){var c=a.MappingInformationType,b=a.ReferenceInformationType;if("NoMappingInformation"===c)return{dataSize:1,buffer:[0],indices:[0],mappingType:"AllSame",referenceType:b};a=a.Materials.a;for(var d=[],e=0;e<a.length;++e)d.push(e);return{dataSize:1,
buffer:a,indices:d,mappingType:c,referenceType:b}}function ea(a){if(void 0===THREE.NURBSCurve)return console.error("THREE.FBXLoader: The loader relies on THREE.NURBSCurve for any nurbs present in the model. Nurbs will show up as empty geometry."),new THREE.BufferGeometry;var c=parseInt(a.Order);if(isNaN(c))return console.error("THREE.FBXLoader: Invalid Order %s given for geometry ID: %s",a.Order,a.id),new THREE.BufferGeometry;--c;for(var b=a.KnotVector.a,d=[],e=a.Points.a,f=0,g=e.length;f<g;f+=4)d.push((new THREE.Vector4).fromArray(e,
f));if("Closed"===a.Form)d.push(d[0]);else if("Periodic"===a.Form){var h=c;var l=b.length-1-h;for(f=0;f<c;++f)d.push(d[f])}a=(new THREE.NURBSCurve(c,b,d,h,l)).getPoints(7*d.length);var k=new Float32Array(3*a.length);a.forEach(function(a,b){a.toArray(k,3*b)});a=new THREE.BufferGeometry;a.addAttribute("position",new THREE.BufferAttribute(k,3));return a}function fa(a,c,b,d,e){var f=new THREE.Group,g=ha(a,b,d,e,c),h=a.Objects.Model;g.forEach(function(b){ia(a,b,h[b.ID],c,f);c.get(b.ID).parents.forEach(function(a){a=
g.get(a.ID);void 0!==a&&a.add(b)});null===b.parent&&f.add(b)});ja(a,b,d,g,c);ka(a,c,f);la(a,f);return f}function ha(a,c,b,d,e){var f=new Map,g=a.Objects.Model,h;for(h in g){var l=parseInt(h),k=g[h],m=e.get(l),n=ma(m,c,l,k.attrName);if(!n){switch(k.attrType){case "Camera":n=na(a,m);break;case "Light":n=oa(a,m);break;case "Mesh":n=pa(a,m,b,d);break;case "NurbsCurve":n=qa(m,b);break;default:n=new THREE.Group}n.name=THREE.PropertyBinding.sanitizeNodeName(k.attrName);n.ID=l}m=n;if("RotationOrder"in k){var q=
"XYZ XZY YZX ZXY YXZ ZYX SphericXYZ".split(" "),r=parseInt(k.RotationOrder.value,10);0<r&&6>r?console.warn("THREE.FBXLoader: unsupported Euler Order: %s. Currently only XYZ order is supported. Animations and rotations may be incorrect.",q[r]):6===r&&console.warn("THREE.FBXLoader: unsupported Euler Order: Spherical XYZ. Animations and rotations may be incorrect.")}"Lcl_Translation"in k&&m.position.fromArray(k.Lcl_Translation.value);"Lcl_Rotation"in k&&(q=k.Lcl_Rotation.value.map(THREE.Math.degToRad),
q.push("ZYX"),m.rotation.fromArray(q));"Lcl_Scaling"in k&&m.scale.fromArray(k.Lcl_Scaling.value);"PreRotation"in k&&(k=k.PreRotation.value.map(THREE.Math.degToRad),k[3]="ZYX",k=(new THREE.Euler).fromArray(k),k=(new THREE.Quaternion).setFromEuler(k),q=(new THREE.Quaternion).setFromEuler(m.rotation),k.multiply(q),m.rotation.setFromQuaternion(k,"ZYX"));f.set(l,n)}return f}function ma(a,c,b,d){var e=null;a.parents.forEach(function(a){for(var f in c){var h=c[f];h.rawBones.forEach(function(c,f){if(c.ID===
a.ID){var g=e;e=new THREE.Bone;e.matrixWorld.copy(c.transformLink);e.name=THREE.PropertyBinding.sanitizeNodeName(d);e.ID=b;h.bones[f]=e;null!==g&&e.add(g)}})}});return e}function na(a,c){var b;c.children.forEach(function(c){c=a.Objects.NodeAttribute[c.ID];void 0!==c&&(b=c)});if(void 0===b)var d=new THREE.Object3D;else{d=0;void 0!==b.CameraProjectionType&&1===b.CameraProjectionType.value&&(d=1);var e=1;void 0!==b.NearPlane&&(e=b.NearPlane.value/1E3);var f=1E3;void 0!==b.FarPlane&&(f=b.FarPlane.value/
1E3);var g=window.innerWidth,h=window.innerHeight;void 0!==b.AspectWidth&&void 0!==b.AspectHeight&&(g=b.AspectWidth.value,h=b.AspectHeight.value);var l=g/h,k=45;void 0!==b.FieldOfView&&(k=b.FieldOfView.value);var m=b.FocalLength?b.FocalLength.value:null;switch(d){case 0:d=new THREE.PerspectiveCamera(k,l,e,f);null!==m&&d.setFocalLength(m);break;case 1:d=new THREE.OrthographicCamera(-g/2,g/2,h/2,-h/2,e,f);break;default:console.warn("THREE.FBXLoader: Unknown camera type "+d+"."),d=new THREE.Object3D}}return d}
function oa(a,c){var b;c.children.forEach(function(c){c=a.Objects.NodeAttribute[c.ID];void 0!==c&&(b=c)});if(void 0===b)var d=new THREE.Object3D;else{var e=void 0===b.LightType?0:b.LightType.value;d=16777215;void 0!==b.Color&&(d=(new THREE.Color).fromArray(b.Color.value));var f=void 0===b.Intensity?1:b.Intensity.value/100;void 0!==b.CastLightOnObject&&0===b.CastLightOnObject.value&&(f=0);var g=0;void 0!==b.FarAttenuationEnd&&(g=void 0!==b.EnableFarAttenuation&&0===b.EnableFarAttenuation.value?0:b.FarAttenuationEnd.value/
1E3);switch(e){case 0:d=new THREE.PointLight(d,f,g,1);break;case 1:d=new THREE.DirectionalLight(d,f);break;case 2:e=Math.PI/3;void 0!==b.InnerAngle&&(e=THREE.Math.degToRad(b.InnerAngle.value));var h=0;void 0!==b.OuterAngle&&(h=THREE.Math.degToRad(b.OuterAngle.value),h=Math.max(h,1));d=new THREE.SpotLight(d,f,g,e,h,1);break;default:console.warn("THREE.FBXLoader: Unknown light type "+b.LightType.value+", defaulting to a THREE.PointLight."),d=new THREE.PointLight(d,f)}void 0!==b.CastShadows&&1===b.CastShadows.value&&
(d.castShadow=!0)}return d}function pa(a,c,b,d){var e=null;a=null;var f=[];c.children.forEach(function(a){b.has(a.ID)&&(e=b.get(a.ID));d.has(a.ID)&&f.push(d.get(a.ID))});1<f.length?a=f:0<f.length?a=f[0]:(a=new THREE.MeshPhongMaterial({color:13421772}),f.push(a));"color"in e.attributes&&f.forEach(function(a){a.vertexColors=THREE.VertexColors});e.FBX_Deformer?(f.forEach(function(a){a.skinning=!0}),c=new THREE.SkinnedMesh(e,a)):c=new THREE.Mesh(e,a);return c}function qa(a,c){var b=a.children.reduce(function(a,
b){c.has(b.ID)&&(a=c.get(b.ID));return a},null),d=new THREE.LineBasicMaterial({color:3342591,linewidth:1});return new THREE.Line(b,d)}function la(a,c){if("GlobalSettings"in a&&"AmbientColor"in a.GlobalSettings){var b=a.GlobalSettings.AmbientColor.value,d=b[0],e=b[1];b=b[2];if(0!==d||0!==e||0!==b)d=new THREE.Color(d,e,b),c.add(new THREE.AmbientLight(d,1))}}function ia(a,c,b,d,e){"LookAtProperty"in b&&d.get(c.ID).children.forEach(function(b){"LookAtProperty"===b.relationship&&(b=a.Objects.Model[b.ID],
"Lcl_Translation"in b&&(b=b.Lcl_Translation.value,void 0!==c.target?(c.target.position.fromArray(b),e.add(c.target)):c.lookAt((new THREE.Vector3).fromArray(b))))})}function ja(a,c,b,d,e){var f=ra(a),g;for(g in c){var h=c[g];e.get(parseInt(h.ID)).parents.forEach(function(a){b.has(a.ID)&&e.get(a.ID).parents.forEach(function(a){d.has(a.ID)&&d.get(a.ID).bind(new THREE.Skeleton(h.bones),f[a.ID])})})}}function ra(a){var c={};if("Pose"in a.Objects){a=a.Objects.Pose;for(var b in a)if("BindPose"===a[b].attrType){var d=
a[b].PoseNode;Array.isArray(d)?d.forEach(function(a){c[a.Node]=(new THREE.Matrix4).fromArray(a.Matrix.a)}):c[d.Node]=(new THREE.Matrix4).fromArray(d.Matrix.a)}}return c}function sa(a,c,b){var d=a.Objects.AnimationLayer,e=new Map,f;for(f in d){var g=[];d=c.get(parseInt(f));void 0!==d&&(d.children.forEach(function(d,e){if(b.has(d.ID)){var f=b.get(d.ID);if(void 0!==f.curves.x||void 0!==f.curves.y||void 0!==f.curves.z){if(void 0===g[e]){var h;c.get(d.ID).parents.forEach(function(a){void 0!==a.relationship&&
(h=a.ID)});var l=a.Objects.Model[h.toString()],q={modelName:THREE.PropertyBinding.sanitizeNodeName(l.attrName),initialPosition:[0,0,0],initialRotation:[0,0,0],initialScale:[1,1,1]};"Lcl_Translation"in l&&(q.initialPosition=l.Lcl_Translation.value);"Lcl_Rotation"in l&&(q.initialRotation=l.Lcl_Rotation.value);"Lcl_Scaling"in l&&(q.initialScale=l.Lcl_Scaling.value);"PreRotation"in l&&(q.preRotations=l.PreRotation.value);g[e]=q}g[e][f.attr]=f}}}),e.set(parseInt(f),g))}return e}function ka(a,c,b){b.animations=
[];if(void 0===a.Objects.AnimationCurve)c=void 0;else{var d=a.Objects.AnimationCurveNode,e=new Map;for(h in d){var f=d[h];null!==f.attrName.match(/S|R|T/)&&(f={id:f.id,attr:f.attrName,curves:{}},e.set(f.id,f))}d=a.Objects.AnimationCurve;for(var g in d){var h={id:d[g].id,times:d[g].KeyTime.a.map(ta),values:d[g].KeyValueFloat.a};var l=c.get(h.id);if(void 0!==l){f=l.parents[0].ID;l=l.parents[0].relationship;if(l.match(/X/))l="x";else if(l.match(/Y/))l="y";else if(l.match(/Z/))l="z";else continue;e.get(f).curves[l]=
h}}e=sa(a,c,e);a=a.Objects.AnimationStack;g={};for(var k in a)d=c.get(parseInt(k)).children,1<d.length&&console.warn("THREE.FBXLoader: Encountered an animation stack with multiple layers, this is currently not supported. Ignoring subsequent layers."),d=e.get(d[0].ID),g[k]={name:a[k].attrName,layer:d};c=g}if(void 0!==c)for(var m in c)k=ua(c[m]),b.animations.push(k)}function ua(a){var c=[];a.layer.forEach(function(a){c=c.concat(va(a))});return new THREE.AnimationClip(a.name,-1,c)}function va(a){var c=
[];if(void 0!==a.T&&0<Object.keys(a.T.curves).length){var b=O(a.modelName,a.T.curves,a.initialPosition,"position");void 0!==b&&c.push(b)}if(void 0!==a.R&&0<Object.keys(a.R.curves).length){b=a.modelName;var d=a.R.curves,e=a.initialRotation,f=a.preRotations;void 0!==d.x&&(d.x.values=d.x.values.map(THREE.Math.degToRad));void 0!==d.y&&(d.y.values=d.y.values.map(THREE.Math.degToRad));void 0!==d.z&&(d.z.values=d.z.values.map(THREE.Math.degToRad));var g=P(d);d=Q(g,d,e);void 0!==f&&(f=f.map(THREE.Math.degToRad),
f.push("ZYX"),f=(new THREE.Euler).fromArray(f),f=(new THREE.Quaternion).setFromEuler(f));e=new THREE.Quaternion;for(var h=new THREE.Euler,l=[],k=0;k<d.length;k+=3)h.set(d[k],d[k+1],d[k+2],"ZYX"),e.setFromEuler(h),void 0!==f&&e.premultiply(f),e.toArray(l,k/3*4);b=new THREE.QuaternionKeyframeTrack(b+".quaternion",g,l);void 0!==b&&c.push(b)}void 0!==a.S&&0<Object.keys(a.S.curves).length&&(a=O(a.modelName,a.S.curves,a.initialScale,"scale"),void 0!==a&&c.push(a));return c}function O(a,c,b,d){var e=P(c);
c=Q(e,c,b);return new THREE.VectorKeyframeTrack(a+"."+d,e,c)}function Q(a,c,b){var d=[],e=-1,f=-1,g=-1;a.forEach(function(a){c.x&&(e=c.x.times.indexOf(a));c.y&&(f=c.y.times.indexOf(a));c.z&&(g=c.z.times.indexOf(a));-1!==e?(a=c.x.values[e],d.push(a),b[0]=a):d.push(b[0]);-1!==f?(a=c.y.values[f],d.push(a),b[1]=a):d.push(b[1]);-1!==g?(a=c.z.values[g],d.push(a),b[2]=a):d.push(b[2])});return d}function P(a){var c=[];void 0!==a.x&&(c=c.concat(a.x.times));void 0!==a.y&&(c=c.concat(a.y.times));void 0!==a.z&&
(c=c.concat(a.z.times));return c=c.sort(function(a,c){return a-c}).filter(function(a,c,e){return e.indexOf(a)==c})}function R(){}function S(){}function H(a,c){this.dv=new DataView(a);this.offset=0;this.littleEndian=void 0!==c?c:!0}function u(){}function T(a){if(a=a.match(/FBXVersion: (\d+)/))return parseInt(a[1]);throw Error("THREE.FBXLoader: Cannot find the version number for the file given.");}function ta(a){return a/46186158E3}function N(a){return a.split(",").map(function(a){return parseFloat(a)})}
function U(a,c,b){void 0===c&&(c=0);void 0===b&&(b=a.byteLength);return THREE.LoaderUtils.decodeText(new Uint8Array(a,c,b))}function wa(a,c){for(var b=0,d=a.length,e=c.length;b<e;b++,d++)a[d]=c[b]}function A(a,c,b,d){for(var e=0;b<d;b++,e++)a[e]=c[b];return a}THREE.FBXLoader=function(a){this.manager=void 0!==a?a:THREE.DefaultLoadingManager};Object.assign(THREE.FBXLoader.prototype,{load:function(a,c,b,d){var e=this,f=THREE.LoaderUtils.extractUrlBase(a),g=new THREE.FileLoader(this.manager);g.setResponseType("arraybuffer");
g.load(a,function(b){try{var g=e.parse(b,f);c(g)}catch(k){window.setTimeout(function(){d&&d(k);e.manager.itemError(a)},0)}},b,d)},parse:function(a,c){if(21<=a.byteLength&&"Kaydara FBX Binary  \x00"===U(a,0,21))var b=(new S).parse(a);else{b=U(a);a:{var d=b;for(var e="Kaydara\\FBX\\Binary\\\\".split(""),f=0,g=0;g<e.length;++g){var h=d[0];d=d.slice(f+1);f++;if(h===e[g]){d=!1;break a}}d=!0}if(!d)throw Error("THREE.FBXLoader: Unknown format.");if(7E3>T(b))throw Error("THREE.FBXLoader: FBX version not supported, FileVersion: "+
T(b));b=(new R).parse(b)}d=V(b);e={};f={};if("Video"in b.Objects){g=b.Objects.Video;for(var l in g){h=g[l];var k=parseInt(l);e[k]=h.Filename;if("Content"in h){var m="string"===typeof h.Content&&""!==h.Content;if(h.Content instanceof ArrayBuffer&&0<h.Content.byteLength||m){a:{var n=g[l];m=n.Content;n=n.RelativeFilename||n.Filename;n=n.slice(n.lastIndexOf(".")+1).toLowerCase();switch(n){case "bmp":n="image/bmp";break;case "jpg":case "jpeg":n="image/jpeg";break;case "png":n="image/png";break;case "tif":n=
"image/tiff";break;default:console.warn('FBXLoader: Image type "'+n+'" is not supported.');m=void 0;break a}"string"===typeof m?m="data:"+n+";base64,"+m:(m=new Uint8Array(m),m=window.URL.createObjectURL(new Blob([m],{type:n})))}f[h.Filename]=m}}}}for(k in e)l=e[k],e[k]=void 0!==f[l]?f[l]:e[k].split("\\").pop();f=b;l=(new THREE.TextureLoader(this.manager)).setPath(c);k=new Map;if("Texture"in f.Objects){f=f.Objects.Texture;for(var q in f){h=void 0;g=f[q];m=l;var r=e;n=m.path;var u=d.get(g.id).children;
void 0!==u&&0<u.length&&void 0!==r[u[0].ID]&&(h=r[u[0].ID],0!==h.indexOf("blob:")&&0!==h.indexOf("data:")||m.setPath(void 0));h=m.load(h);m.setPath(n);h.ID=g.id;h.name=g.attrName;m=g.WrapModeU;n=g.WrapModeV;n=void 0!==n?n.value:0;h.wrapS=0===(void 0!==m?m.value:0)?THREE.RepeatWrapping:THREE.ClampToEdgeWrapping;h.wrapT=0===n?THREE.RepeatWrapping:THREE.ClampToEdgeWrapping;"Scaling"in g&&(g=g.Scaling.value,h.repeat.x=g[0],h.repeat.y=g[1]);g=h;k.set(parseInt(q),g)}}e=b;q=new Map;if("Material"in e.Objects){l=
e.Objects.Material;for(var w in l){h=e;m=l[w];n=k;r=d;u=m.id;f=m.attrName;g=m.ShadingModel;"object"===typeof g&&(g=g.value);if(r.has(u)){h=W(h,m,n,u,r);switch(g.toLowerCase()){case "phong":g=new THREE.MeshPhongMaterial;break;case "lambert":g=new THREE.MeshLambertMaterial;break;default:console.warn('THREE.FBXLoader: unknown material type "%s". Defaulting to MeshPhongMaterial.',g),g=new THREE.MeshPhongMaterial({color:3342591})}g.setValues(h);g.name=f;f=g}else f=null;null!==f&&q.set(parseInt(w),f)}}w=
{};if("Deformer"in b.Objects){e=b.Objects.Deformer;for(var x in e)"Skin"===e[x].attrType&&(k=d.get(parseInt(x)),l=X(k,e),l.ID=x,1<k.parents.length&&console.warn("THREE.FBXLoader: skeleton attached to more than one geometry is not supported."),l.geometryID=k.parents[0].ID,w[x]=l)}x=b;e=new Map;if("Geometry"in x.Objects){k=x.Objects.Geometry;for(var v in k){l=d.get(parseInt(v));a:{f=k[v];switch(f.attrType){case "Mesh":l=Y(x,l,f,w);break a;case "NurbsCurve":l=ea(f);break a}l=void 0}e.set(parseInt(v),
l)}}return fa(b,d,w,e,q)}});var F=[],K={ByPolygonVertex:{Direct:function(a,c,b,d){return A(F,d.buffer,a*d.dataSize,a*d.dataSize+d.dataSize)},IndexToDirect:function(a,c,b,d){a=d.indices[a];return A(F,d.buffer,a*d.dataSize,a*d.dataSize+d.dataSize)}},ByPolygon:{Direct:function(a,c,b,d){return A(F,d.buffer,c*d.dataSize,c*d.dataSize+d.dataSize)},IndexToDirect:function(a,c,b,d){a=d.indices[c];return A(F,d.buffer,a*d.dataSize,a*d.dataSize+d.dataSize)}},ByVertice:{Direct:function(a,c,b,d){return A(F,d.buffer,
b*d.dataSize,b*d.dataSize+d.dataSize)}},AllSame:{IndexToDirect:function(a,c,b,d){return A(F,d.buffer,d.indices[0]*d.dataSize,d.indices[0]*d.dataSize+d.dataSize)}}};Object.assign(R.prototype,{getPrevNode:function(){return this.nodeStack[this.currentIndent-2]},getCurrentNode:function(){return this.nodeStack[this.currentIndent-1]},getCurrentProp:function(){return this.currentProp},pushStack:function(a){this.nodeStack.push(a);this.currentIndent+=1},popStack:function(){this.nodeStack.pop();--this.currentIndent},
setCurrentProp:function(a,c){this.currentProp=a;this.currentPropName=c},parse:function(a){this.currentIndent=0;this.allNodes=new u;this.nodeStack=[];this.currentProp=[];this.currentPropName="";var c=this,b=a.split("\n");b.forEach(function(a,e){var d=a.match(/^[\s\t]*;/),g=a.match(/^[\s\t]*$/);if(!d&&!g){d=a.match("^\\t{"+c.currentIndent+"}(\\w+):(.*){","");g=a.match("^\\t{"+c.currentIndent+"}(\\w+):[\\s\\t\\r\\n](.*)");var h=a.match("^\\t{"+(c.currentIndent-1)+"}}");d?c.parseNodeBegin(a,d):g?c.parseNodeProperty(a,
g,b[++e]):h?c.popStack():a.match(/^[^\s\t}]/)&&c.parseNodePropertyContinued(a)}});return this.allNodes},parseNodeBegin:function(a,c){var b=c[1].trim().replace(/^"/,"").replace(/"$/,""),d=c[2].split(",").map(function(a){return a.trim().replace(/^"/,"").replace(/"$/,"")}),e={name:b};d=this.parseNodeAttr(d);var f=this.getCurrentNode();0===this.currentIndent?this.allNodes.add(b,e):b in f?("PoseNode"===b?f.PoseNode.push(e):void 0!==f[b].id&&(f[b]={},f[b][f[b].id]=f[b]),""!==d.id&&(f[b][d.id]=e)):"number"===
typeof d.id?(f[b]={},f[b][d.id]=e):"Properties70"!==b&&(f[b]="PoseNode"===b?[e]:e);"number"===typeof d.id&&(e.id=d.id);""!==d.name&&(e.attrName=d.name);""!==d.type&&(e.attrType=d.type);this.pushStack(e)},parseNodeAttr:function(a){var c=a[0];""!==a[0]&&(c=parseInt(a[0]),isNaN(c)&&(c=a[0]));var b="",d="";1<a.length&&(b=a[1].replace(/^(\w+)::/,""),d=a[2]);return{id:c,name:b,type:d}},parseNodeProperty:function(a,c,b){var d=c[1].replace(/^"/,"").replace(/"$/,"").trim();c=c[2].replace(/^"/,"").replace(/"$/,
"").trim();"Content"===d&&","===c&&(c=b.replace(/"/g,"").replace(/,$/,"").trim());b=this.getCurrentNode();if("Properties70"===b.name)this.parseNodeSpecialProperty(a,d,c);else{if("C"===d){d=c.split(",").slice(1);a=parseInt(d[0]);var e=parseInt(d[1]),f=c.split(",").slice(3);f=f.map(function(a){return a.trim().replace(/^"/,"")});d="connections";c=[a,e];wa(c,f);void 0===b[d]&&(b[d]=[])}"Node"===d&&(b.id=c);d in b&&Array.isArray(b[d])?b[d].push(c):"a"!==d?b[d]=c:b.a=c;this.setCurrentProp(b,d);"a"===d&&
","!==c.slice(-1)&&(b.a=N(c))}},parseNodePropertyContinued:function(a){var c=this.getCurrentNode();c.a+=a;","!==a.slice(-1)&&(c.a=N(c.a))},parseNodeSpecialProperty:function(a,c,b){var d=b.split('",').map(function(a){return a.trim().replace(/^"/,"").replace(/\s/,"_")});a=d[0];c=d[1];b=d[2];var e=d[3];d=d[4];switch(c){case "int":case "enum":case "bool":case "ULongLong":case "double":case "Number":case "FieldOfView":d=parseFloat(d);break;case "Color":case "ColorRGB":case "Vector3D":case "Lcl_Translation":case "Lcl_Rotation":case "Lcl_Scaling":d=
N(d)}this.getPrevNode()[a]={type:c,type2:b,flag:e,value:d};this.setCurrentProp(this.getPrevNode(),a)}});Object.assign(S.prototype,{parse:function(a){a=new H(a);a.skip(23);for(var c=a.getUint32(),b=new u;!this.endOfContent(a);){var d=this.parseNode(a,c);null!==d&&b.add(d.name,d)}return b},endOfContent:function(a){return 0===a.size()%16?(a.getOffset()+160+16&-16)>=a.size():a.getOffset()+160+16>=a.size()},parseNode:function(a,c){var b={},d=7500<=c?a.getUint64():a.getUint32(),e=7500<=c?a.getUint64():
a.getUint32();7500<=c?a.getUint64():a.getUint32();var f=a.getUint8();f=a.getString(f);if(0===d)return null;for(var g=[],h=0;h<e;h++)g.push(this.parseProperty(a));h=0<g.length?g[0]:"";var l=1<g.length?g[1]:"",k=2<g.length?g[2]:"";for(b.singleProperty=1===e&&a.getOffset()===d?!0:!1;d>a.getOffset();)e=this.parseNode(a,c),null!==e&&this.parseSubNode(f,b,e);b.propertyList=g;"number"===typeof h&&(b.id=h);""!==l&&(b.attrName=l);""!==k&&(b.attrType=k);""!==f&&(b.name=f);return b},parseSubNode:function(a,
c,b){if(!0===b.singleProperty)a=b.propertyList[0],Array.isArray(a)?(c[b.name]=b,b.a=a):c[b.name]=a;else if("Connections"===a&&"C"===b.name){var d=[];b.propertyList.forEach(function(a,b){0!==b&&d.push(a)});void 0===c.connections&&(c.connections=[]);c.connections.push(d)}else if("Properties70"===b.name)Object.keys(b).forEach(function(a){c[a]=b[a]});else if("Properties70"===a&&"P"===b.name){a=b.propertyList[0];var e=b.propertyList[1],f=b.propertyList[2],g=b.propertyList[3];0===a.indexOf("Lcl ")&&(a=
a.replace("Lcl ","Lcl_"));0===e.indexOf("Lcl ")&&(e=e.replace("Lcl ","Lcl_"));var h="Color"===e||"ColorRGB"===e||"Vector"===e||"Vector3D"===e||0===e.indexOf("Lcl_")?[b.propertyList[4],b.propertyList[5],b.propertyList[6]]:b.propertyList[4];c[a]={type:e,type2:f,flag:g,value:h}}else void 0===c[b.name]?"number"===typeof b.id?(c[b.name]={},c[b.name][b.id]=b):c[b.name]=b:"PoseNode"===b.name?(Array.isArray(c[b.name])||(c[b.name]=[c[b.name]]),c[b.name].push(b)):void 0===c[b.name][b.id]&&(c[b.name][b.id]=
b)},parseProperty:function(a){var c=a.getString(1);switch(c){case "C":return a.getBoolean();case "D":return a.getFloat64();case "F":return a.getFloat32();case "I":return a.getInt32();case "L":return a.getInt64();case "R":return c=a.getUint32(),a.getArrayBuffer(c);case "S":return c=a.getUint32(),a.getString(c);case "Y":return a.getInt16();case "b":case "c":case "d":case "f":case "i":case "l":var b=a.getUint32(),d=a.getUint32(),e=a.getUint32();if(0===d)switch(c){case "b":case "c":return a.getBooleanArray(b);
case "d":return a.getFloat64Array(b);case "f":return a.getFloat32Array(b);case "i":return a.getInt32Array(b);case "l":return a.getInt64Array(b)}void 0===window.Zlib&&console.error("THREE.FBXLoader: External library Inflate.min.js required, obtain or import from https://github.com/imaya/zlib.js");a=new Zlib.Inflate(new Uint8Array(a.getArrayBuffer(e)));a=new H(a.decompress().buffer);switch(c){case "b":case "c":return a.getBooleanArray(b);case "d":return a.getFloat64Array(b);case "f":return a.getFloat32Array(b);
case "i":return a.getInt32Array(b);case "l":return a.getInt64Array(b)}default:throw Error("THREE.FBXLoader: Unknown property type "+c);}}});Object.assign(H.prototype,{getOffset:function(){return this.offset},size:function(){return this.dv.buffer.byteLength},skip:function(a){this.offset+=a},getBoolean:function(){return 1===(this.getUint8()&1)},getBooleanArray:function(a){for(var c=[],b=0;b<a;b++)c.push(this.getBoolean());return c},getUint8:function(){var a=this.dv.getUint8(this.offset);this.offset+=
1;return a},getInt16:function(){var a=this.dv.getInt16(this.offset,this.littleEndian);this.offset+=2;return a},getInt32:function(){var a=this.dv.getInt32(this.offset,this.littleEndian);this.offset+=4;return a},getInt32Array:function(a){for(var c=[],b=0;b<a;b++)c.push(this.getInt32());return c},getUint32:function(){var a=this.dv.getUint32(this.offset,this.littleEndian);this.offset+=4;return a},getInt64:function(){if(this.littleEndian){var a=this.getUint32();var c=this.getUint32()}else c=this.getUint32(),
a=this.getUint32();return c&2147483648?(c=~c&4294967295,a=~a&4294967295,4294967295===a&&(c=c+1&4294967295),-(4294967296*c+(a+1&4294967295))):4294967296*c+a},getInt64Array:function(a){for(var c=[],b=0;b<a;b++)c.push(this.getInt64());return c},getUint64:function(){if(this.littleEndian){var a=this.getUint32();var c=this.getUint32()}else c=this.getUint32(),a=this.getUint32();return 4294967296*c+a},getFloat32:function(){var a=this.dv.getFloat32(this.offset,this.littleEndian);this.offset+=4;return a},getFloat32Array:function(a){for(var c=
[],b=0;b<a;b++)c.push(this.getFloat32());return c},getFloat64:function(){var a=this.dv.getFloat64(this.offset,this.littleEndian);this.offset+=8;return a},getFloat64Array:function(a){for(var c=[],b=0;b<a;b++)c.push(this.getFloat64());return c},getArrayBuffer:function(a){var c=this.dv.buffer.slice(this.offset,this.offset+a);this.offset+=a;return c},getString:function(a){for(var c=new Uint8Array(a),b=0;b<a;b++)c[b]=this.getUint8();a=c.indexOf(0);0<=a&&(c=c.slice(0,a));return THREE.LoaderUtils.decodeText(c)}});
Object.assign(u.prototype,{add:function(a,c){this[a]=c}})})();
